# Generated by Django 2.2.2 on 2019-09-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.FloatField(help_text='Enter company name', max_length=60)),
                ('matching_tolerance', models.FloatField(default=0.6)),
                ('company_logo', models.ImageField(default='images/company_logo.jpg', upload_to='images/')),
            ],
        ),
    ]
