# Generated by Django 2.2.2 on 2019-09-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websettings',
            name='company_name',
            field=models.CharField(help_text='Enter company name', max_length=60),
        ),
    ]
