# Generated by Django 2.2.2 on 2019-09-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190917_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
