# Generated by Django 2.2.2 on 2019-09-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190917_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='footer_color',
            field=models.CharField(default='000000', help_text='Enter company primary color hexa code without #', max_length=6),
        ),
        migrations.AddField(
            model_name='websettings',
            name='header_color',
            field=models.CharField(default='000000', help_text='Enter company primary color hexa code without #', max_length=6),
        ),
    ]
