# Generated by Django 2.2.2 on 2019-09-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190917_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='text_color',
            field=models.CharField(default='000000', help_text='Enter company primary color hexa code without #', max_length=6),
        ),
    ]
