# Generated by Django 2.2.2 on 2019-09-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190917_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='website_background_color',
            field=models.CharField(default='FFFFFF', help_text='Enter company background color hexa code without #', max_length=6),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='footer_color',
            field=models.CharField(default='000000', help_text='Enter company footer color hexa code without #', max_length=6),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='footer_text',
            field=models.CharField(help_text='Enter company footer text.', max_length=60),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='footer_text_color',
            field=models.CharField(default='000000', help_text='Enter company footer text color hexa code without #', max_length=6),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='header_color',
            field=models.CharField(default='000000', help_text='Enter company header color hexa code without #', max_length=6),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='text_color',
            field=models.CharField(default='000000', help_text='Enter company text color hexa code without #', max_length=6),
        ),
    ]
