# Generated by Django 2.2.2 on 2019-09-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_websettings_website_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='failure_message_body',
            field=models.CharField(default='test', help_text='Failure message body on match.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websettings',
            name='failure_message_title',
            field=models.CharField(default='test', help_text='Failure message title on match.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websettings',
            name='success_message_body',
            field=models.CharField(default='test', help_text='Success message body on match.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websettings',
            name='success_message_title',
            field=models.CharField(default='test', help_text='Success message title on match.', max_length=200),
            preserve_default=False,
        ),
    ]
