# Generated by Django 2.2.2 on 2019-09-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190919_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='next_button_color',
            field=models.CharField(default='000000', help_text='Enter next button color hexa code without #', max_length=6),
        ),
        migrations.AddField(
            model_name='websettings',
            name='next_button_text_color',
            field=models.CharField(default='000000', help_text='Enter next button text color hexa code without #', max_length=6),
        ),
    ]
